//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Academics.LocalHostReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LocalHostReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertStudent", ReplyAction="http://tempuri.org/IService1/InsertStudentResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="_status")]
        string InsertStudent(LogicLayer.DTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertStudent", ReplyAction="http://tempuri.org/IService1/InsertStudentResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="_status")]
        System.Threading.Tasks.Task<string> InsertStudentAsync(LogicLayer.DTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateStudent", ReplyAction="http://tempuri.org/IService1/UpdateStudentResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="_status")]
        string UpdateStudent(LogicLayer.DTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateStudent", ReplyAction="http://tempuri.org/IService1/UpdateStudentResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="_status")]
        System.Threading.Tasks.Task<string> UpdateStudentAsync(LogicLayer.DTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteStudent", ReplyAction="http://tempuri.org/IService1/DeleteStudentResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="_status")]
        string DeleteStudent(LogicLayer.DTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteStudent", ReplyAction="http://tempuri.org/IService1/DeleteStudentResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="_status")]
        System.Threading.Tasks.Task<string> DeleteStudentAsync(LogicLayer.DTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStudentDatatable", ReplyAction="http://tempuri.org/IService1/GetStudentDatatableResponse")]
        LogicLayer.DTO[] GetStudentDatatable();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStudentDatatable", ReplyAction="http://tempuri.org/IService1/GetStudentDatatableResponse")]
        System.Threading.Tasks.Task<LogicLayer.DTO[]> GetStudentDatatableAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/callSearch", ReplyAction="http://tempuri.org/IService1/callSearchResponse")]
        LogicLayer.DTO[] callSearch(string searchText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/callSearch", ReplyAction="http://tempuri.org/IService1/callSearchResponse")]
        System.Threading.Tasks.Task<LogicLayer.DTO[]> callSearchAsync(string searchText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertMarks", ReplyAction="http://tempuri.org/IService1/InsertMarksResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="_status")]
        string InsertMarks(LogicLayer.DTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertMarks", ReplyAction="http://tempuri.org/IService1/InsertMarksResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="_status")]
        System.Threading.Tasks.Task<string> InsertMarksAsync(LogicLayer.DTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateMarks", ReplyAction="http://tempuri.org/IService1/UpdateMarksResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="_status")]
        string UpdateMarks(LogicLayer.DTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateMarks", ReplyAction="http://tempuri.org/IService1/UpdateMarksResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="_status")]
        System.Threading.Tasks.Task<string> UpdateMarksAsync(LogicLayer.DTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteMarks", ReplyAction="http://tempuri.org/IService1/DeleteMarksResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="_status")]
        string DeleteMarks(LogicLayer.DTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteMarks", ReplyAction="http://tempuri.org/IService1/DeleteMarksResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="_status")]
        System.Threading.Tasks.Task<string> DeleteMarksAsync(LogicLayer.DTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMarksDatatable", ReplyAction="http://tempuri.org/IService1/GetMarksDatatableResponse")]
        LogicLayer.DTO[] GetMarksDatatable();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMarksDatatable", ReplyAction="http://tempuri.org/IService1/GetMarksDatatableResponse")]
        System.Threading.Tasks.Task<LogicLayer.DTO[]> GetMarksDatatableAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/callSearchMarks", ReplyAction="http://tempuri.org/IService1/callSearchMarksResponse")]
        LogicLayer.DTO[] callSearchMarks(string searchText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/callSearchMarks", ReplyAction="http://tempuri.org/IService1/callSearchMarksResponse")]
        System.Threading.Tasks.Task<LogicLayer.DTO[]> callSearchMarksAsync(string searchText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSemesterDatatable", ReplyAction="http://tempuri.org/IService1/GetSemesterDatatableResponse")]
        LogicLayer.DTO[] GetSemesterDatatable();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSemesterDatatable", ReplyAction="http://tempuri.org/IService1/GetSemesterDatatableResponse")]
        System.Threading.Tasks.Task<LogicLayer.DTO[]> GetSemesterDatatableAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSubjectsDatatable", ReplyAction="http://tempuri.org/IService1/GetSubjectsDatatableResponse")]
        LogicLayer.DTO[] GetSubjectsDatatable();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSubjectsDatatable", ReplyAction="http://tempuri.org/IService1/GetSubjectsDatatableResponse")]
        System.Threading.Tasks.Task<LogicLayer.DTO[]> GetSubjectsDatatableAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Academics.LocalHostReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Academics.LocalHostReference.IService1>, Academics.LocalHostReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string InsertStudent(LogicLayer.DTO dto) {
            return base.Channel.InsertStudent(dto);
        }
        
        public System.Threading.Tasks.Task<string> InsertStudentAsync(LogicLayer.DTO dto) {
            return base.Channel.InsertStudentAsync(dto);
        }
        
        public string UpdateStudent(LogicLayer.DTO dto) {
            return base.Channel.UpdateStudent(dto);
        }
        
        public System.Threading.Tasks.Task<string> UpdateStudentAsync(LogicLayer.DTO dto) {
            return base.Channel.UpdateStudentAsync(dto);
        }
        
        public string DeleteStudent(LogicLayer.DTO dto) {
            return base.Channel.DeleteStudent(dto);
        }
        
        public System.Threading.Tasks.Task<string> DeleteStudentAsync(LogicLayer.DTO dto) {
            return base.Channel.DeleteStudentAsync(dto);
        }
        
        public LogicLayer.DTO[] GetStudentDatatable() {
            return base.Channel.GetStudentDatatable();
        }
        
        public System.Threading.Tasks.Task<LogicLayer.DTO[]> GetStudentDatatableAsync() {
            return base.Channel.GetStudentDatatableAsync();
        }
        
        public LogicLayer.DTO[] callSearch(string searchText) {
            return base.Channel.callSearch(searchText);
        }
        
        public System.Threading.Tasks.Task<LogicLayer.DTO[]> callSearchAsync(string searchText) {
            return base.Channel.callSearchAsync(searchText);
        }
        
        public string InsertMarks(LogicLayer.DTO dto) {
            return base.Channel.InsertMarks(dto);
        }
        
        public System.Threading.Tasks.Task<string> InsertMarksAsync(LogicLayer.DTO dto) {
            return base.Channel.InsertMarksAsync(dto);
        }
        
        public string UpdateMarks(LogicLayer.DTO dto) {
            return base.Channel.UpdateMarks(dto);
        }
        
        public System.Threading.Tasks.Task<string> UpdateMarksAsync(LogicLayer.DTO dto) {
            return base.Channel.UpdateMarksAsync(dto);
        }
        
        public string DeleteMarks(LogicLayer.DTO dto) {
            return base.Channel.DeleteMarks(dto);
        }
        
        public System.Threading.Tasks.Task<string> DeleteMarksAsync(LogicLayer.DTO dto) {
            return base.Channel.DeleteMarksAsync(dto);
        }
        
        public LogicLayer.DTO[] GetMarksDatatable() {
            return base.Channel.GetMarksDatatable();
        }
        
        public System.Threading.Tasks.Task<LogicLayer.DTO[]> GetMarksDatatableAsync() {
            return base.Channel.GetMarksDatatableAsync();
        }
        
        public LogicLayer.DTO[] callSearchMarks(string searchText) {
            return base.Channel.callSearchMarks(searchText);
        }
        
        public System.Threading.Tasks.Task<LogicLayer.DTO[]> callSearchMarksAsync(string searchText) {
            return base.Channel.callSearchMarksAsync(searchText);
        }
        
        public LogicLayer.DTO[] GetSemesterDatatable() {
            return base.Channel.GetSemesterDatatable();
        }
        
        public System.Threading.Tasks.Task<LogicLayer.DTO[]> GetSemesterDatatableAsync() {
            return base.Channel.GetSemesterDatatableAsync();
        }
        
        public LogicLayer.DTO[] GetSubjectsDatatable() {
            return base.Channel.GetSubjectsDatatable();
        }
        
        public System.Threading.Tasks.Task<LogicLayer.DTO[]> GetSubjectsDatatableAsync() {
            return base.Channel.GetSubjectsDatatableAsync();
        }
    }
}
